name = "AlcyonValue"
uuid = "8e141ef3-93ad-4b93-8838-3aa69831e2fc"
authors = ["Alcyon Lab"]
version = "1.0.2-DEV"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"

[compat]
julia = "1.2"
